main: net.jandie1505.playerlevels.cloudnet.PlayerLevelsCloudNet
name: PlayerLevels-CloudNet
version: 1.0
api-version: 1.19
depend: ['PlayerLevels', 'CloudNet-Bridge']
author: jandie1505
website: https://jandie1505.github.io/PlayerLevels