main: net.jandie1505.playerlevels.core.PlayerLevels
name: PlayerLevels
version: 1.0
api-version: 1.19
commands:
  levels:
    description: Plugin command
    aliases: ['playerlevels','level']
permissions:
  playerlevels.admin:
    default: op
    description: Access to all commands
  playerlevels.manage_players:
    default: op
    description: Manage player data
  playerlevels.manage_rewards:
    default: op
    description: Manage rewards
  playerlevels.toplist:
    description: Use /levels top
  playerlevels.command.rewards:
    description: Show milestones using /levels milestones
  playerlevels.info.view_other:
    description: Show leveling information of other players using /levels info PLAYER
  playerlevels.use:
    description: Use /levels in general
  playerlevels.*:
    description: Wildcard permission which grants all permissions
    default: op
    children: ['playerlevels.admin']
softdepend: ['LuckPerms']