main: net.jandie1505.playerlevels.core.PlayerLevels
name: PlayerLevels
version: 1.0
api-version: 1.19
commands:
  levels:
    description: Plugin command
    aliases: ['playerlevels','level']
permissions:
  playerlevels.admin:
    default: op
