site_name: PlayerLevels
site_url: https://jandie1505.github.io/PlayerLevels/
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Setup:
    - Installation: installation.md
  - Plugin usage:
    - Leveling: leveling.md
    - Rewards: rewards.md
    - Commands: commands.md
  - API:
      - Getting started: api-getting-started.md
      - Players: api-players.md
      - Rewards: api-rewards.md
  - Integrations:
      - PlaceholderAPI: integrations-placeholderapi.md

markdown_extensions:
  - toc
  - admonition
  - codehilite
